### ISSUE TITLE
SuSFS refactor for newer GKI kernels

### ISSUE THREAD

**Issue by privacyguy123** [dev-sm8350/susfs4ksu#1]
Sorry I wasn't sure how else to get in contact ...

I noticed you seemed to have some success making some changes to the code to get it working on newer kernel version ... I helped Simon test the original version on my 4.19 extensively but it is time I upgraded. Along with learning how to work with this new GKI stuff I noticed a LOT of build errors trying to integrate SuSFS to 5.15 GKI kernel for Google Pixel 8 Pro. I wonder could you reach out via Telegram perhaps to offer some of your knowledge to get this working for more/newer devices? :)

@privacyguy123

**Comment by TogoFire** [comment]
> Sorry I wasn't sure how else to get in contact ...
> 
> I noticed you seemed to have some success making some changes to the code to get it working on newer kernel version ... I helped Simon test the original version on my 4.19 extensively but it is time I upgraded. Along with learning how to work with this new GKI stuff I noticed a LOT of build errors trying to integrate SuSFS to 5.15 GKI kernel for Google Pixel 8 Pro. I wonder could you reach out via Telegram perhaps to offer some of your knowledge to get this working for more/newer devices? :)
> 
> @privacyguy123

Np.

https://t.me/stuff_android/378

https://t.me/TogoFire

https://github.com/dev-sm8350/kernel_oneplus_sm8350

https://github.com/dev-sm8350/kernel_oneplus_sm8350/commit/4d82804100c989d99381b047d36ee89cff34b4a0

https://prnt.sc/9cR8x2GElEIC

Git Commands: https://t.me/stuff_android/363

**Comment by TogoFire** [comment]
New:

**Comment by TogoFire** [comment]
New:
https://github.com/dev-sm8350/kernel_oneplus_sm8350/commit/38ace7afbf6b8975437dbe2cd6afc8876359cf6f
https://github.com/dev-sm8350/kernel_oneplus_sm8350/commit/06f59e2283cff7aaed4a5ffd70e5cee4d46035ef
https://github.com/dev-sm8350/kernel_oneplus_sm8350/commit/ed50b2ea4517bba1396bf7c3aff22c1a8de82aba
https://github.com/dev-sm8350/kernel_oneplus_sm8350/commit/ac36a829c399a6b9c81ae1e14fc20b6fadc2b07f
https://github.com/dev-sm8350/kernel_oneplus_sm8350/commit/ac36a829c399a6b9c81ae1e14fc20b6fadc2b07f
